MIGRATION_URL: http://localhost:8081/oldclient

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: "prometheus, health"
  endpoint:
    health:
      probes:
        enabled: true
